services:
  php:
    build:
      args:
        user: www
        group: www
        uid: 1000
        gid: 1000
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/bank
    container_name: bank_php
    depends_on:
      - postgres
  nginx:
    image: nginx:stable-alpine
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .:/var/www/bank
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: bank_nginx
    depends_on:
        - php
  postgres:
    image: postgres:17.0
    ports:
      - ${PG_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: bank_postgres

volumes:
  pgdata: